In [34]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#1. 패키지 설치 및 불러오기

In [35]:
!pip install jamo

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: jamo in /usr/local/lib/python3.9/dist-packages (0.4.1)

In [36]:
import os
import pandas as pd
import jamo
from jamo import h2j, j2hcj

#2. 종성 함수 만들기

In [37]:
def get_jongsung_TF(sample_text):
    sample_text_list = list(sample_text)
    last_word = sample_text_list[-1]
    last_word_jamo_list = list(j2hcj(h2j(last_word)))
    last_jamo = last_word_jamo_list[-1]

    jongsung_TF = "T"

    if last_jamo in ['ㅏ', 'ㅑ', 'ㅓ', 'ㅕ', 'ㅗ', 'ㅛ', 'ㅜ', 'ㅠ', 'ㅡ', 'ㅣ', 'ㅘ', 'ㅚ', 'ㅙ', 'ㅝ', 'ㅞ', 'ㅢ', 'ㅐ,ㅔ', 'ㅟ', 'ㅖ', 'ㅒ']:
        jongsung_TF = "F"

    return jongsung_TF

#3. 종성 함수 적용

In [38]:
# 데이터 불러오기
dict_notf = pd.read_csv('/content/drive/MyDrive/menu_labelling/dictionaries/dict1_v1_0.csv')
dict_notf.head()

,<surface>,<left_context_id>,<right_context_id>,<cost>,<pos>,<semantic>,<has_jongseong>,<reading>,<type>,<start_pos>,<end_pos>,<expression>
0,가나,0,0,0.0,NNG,*,F,가나,*,*,*,*
1,가나슈,0,0,0.0,NNG,*,F,가나슈,*,*,*,*
2,가또,0,0,0.0,NNG,*,F,가또,*,*,*,*
3,가라아게,0,0,0.0,NNG,*,T,가라아게,*,*,*,*
4,가라아게동,0,0,0.0,NNG,*,T,가라아게동,*,*,*,*

In [39]:
dict_notf['<has_jongseong>'] = dict_notf['<surface>'].apply(get_jongsung_TF)

In [40]:
dict_notf.head()

,<surface>,<left_context_id>,<right_context_id>,<cost>,<pos>,<semantic>,<has_jongseong>,<reading>,<type>,<start_pos>,<end_pos>,<expression>
0,가나,0,0,0.0,NNG,*,F,가나,*,*,*,*
1,가나슈,0,0,0.0,NNG,*,F,가나슈,*,*,*,*
2,가또,0,0,0.0,NNG,*,F,가또,*,*,*,*
3,가라아게,0,0,0.0,NNG,*,T,가라아게,*,*,*,*
4,가라아게동,0,0,0.0,NNG,*,T,가라아게동,*,*,*,*

#4. 데이저 저장

In [41]:
dict_notf.to_csv('/content/drive/MyDrive/menu_labelling/dictionaries/dict1_v1_1.csv',index=False)